### ISSUE TITLE
Last character print issue

### ISSUE THREAD

**Issue by craftersmine** [oneir0mancer/tmpro-custom-tags#2]
**Issue:** typewriter animator doesn't print last character of the text.

**How to reproduce:**
1. Add TMPro Text Object
2. Write sample text
3. Start animation (either with "Play on start" or by running it using "Play()")

**What happens:** last character remains truncated, and doesn't show up.
**What expected:** every character be printed as expected.

**How to temporary fix it:** add any character at the end of the text, for example a space.

**Screenshots:**
Expected text:
![image](https://github.com/user-attachments/assets/fea82a98-2389-4256-be72-e9be3c6d07ba)
After running a Typewriter animation on it (exclamation character is missing):
![image](https://github.com/user-attachments/assets/4c8f0571-bbd8-4e74-a565-1d53bb8f249a)

**Comment by oneir0mancer** [comment]
It has something to do with subscribing to TMPro_EventManager.TEXT_CHANGED_EVENT and internal TMP logic. I.e. when TagParser component is present it works fine.
For now I added a bool field to mark whether the animated text is used by TagParser or not.
